name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        env:
          NEXT_PUBLIC_IMAGE_SERVER: https://server.styleswap.art/  # The public image server address.
          NEXTAUTH_SECRET: "randomSecret"
        with:
          build: npm run build
          start: npm start
          wait-on: "http://localhost:3000"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-downloads
          path: |
            cypress/downloads
           